services:
  stf:
    user: root
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - SCREEN_GRABBER=minicap-bin
      - DEVICE_FARM_URL=http://127.0.0.1:8000/android
      - FARM_IS_TV_MODE=false
    command: >
      sh -c "cd /app &&
      npm install --quiet --no-audit --no-fund &&
      exec node_modules/.bin/nodemon"
