version: "3"

services:
  rethinkdb:
    container_name: rethinkdb
    image: rethinkdb:2.4.2
    restart: unless-stopped
    volumes:
        - "rethinkdb-data:/data"
    command: "rethinkdb --bind all --cache-size 2048"

  adb:
    container_name: adb
    image: devicefarmer/adb:latest
    restart: unless-stopped
    volumes:
      - "/dev/bus/usb:/dev/bus/usb"
    privileged: true

  stf:
    container_name: stf
    image: 96bb7b7c557c
    ports:
      - "7100:7100"
      - "7110:7110"
      - "7400-7500:7400-7500"
    environment:
      - TZ='Europe/Moscow'
      - RETHINKDB_PORT_28015_TCP=tcp://rethinkdb:28015
      - SCREEN_GRABBER=minicap-bin
      - DEVICE_FARM_URL=http://device-ranch.spb.dc/android/
      - FARM_IS_TV_MODE=false
    restart: unless-stopped
    command: stf local --port 443 --adb-host adb --provider-min-port 7400 --provider-max-port 7500

volumes:
  rethinkdb-data: {}
